import com.fasterxml.jackson.databind.ObjectMapper;
import org.jsoup.Jsoup;

import java.io.IOException;

public class JsoupJson_02day_05 {

    public static void main(String[] args) throws IOException {
        String movieName = "Terminator";
        String jsonString = Jsoup.connect("https://itunes.apple.com/search?media=movie&term=" + movieName)
                .ignoreContentType(true)
                .execute()
                .body();
        //System.out.println(jsonString);
        ObjectMapper objectMapper = new ObjectMapper();
        var jsonNode = objectMapper.readTree(jsonString);
        String resultUrl = jsonNode.get("results").get(0).get("previewUrl").asText();
        System.out.println(resultUrl);
    }
}
//jsonNode.get("results").get(0).get("previewUrl")

//{
//  "resultCount": 9,
//  "results": [
//    {
//      "wrapperType": "track",
//      "kind": "feature-movie",
//      "trackId": 271991087,
//      "artistName": "James Cameron",
//      "trackName": "The Terminator",
//      "trackCensoredName": "The Terminator",
//      "trackViewUrl": "https://itunes.apple.com/us/movie/the-terminator/id271991087?uo=4",
//      "previewUrl": "https://video-ssl.itunes.apple.com/itunes-assets/Video118/v4/56/45/78/564578c5-6aef-873a-fda6-31b57bb7a69b/mzvf_5386172920251510773.640x460.h264lc.U.p.m4v",
//      "artworkUrl30": "https://is1-ssl.mzstatic.com/image/thumb/Video128/v4/6a/64/74/6a647480-3d2b-c40f-0901-d5b30b35ea45/pr_source.lsr/30x30bb.jpg",
//      "artworkUrl60": "https://is1-ssl.mzstatic.com/image/thumb/Video128/v4/6a/64/74/6a647480-3d2b-c40f-0901-d5b30b35ea45/pr_source.lsr/60x60bb.jpg",
//      "artworkUrl100": "https://is1-ssl.mzstatic.com/image/thumb/Video128/v4/6a/64/74/6a647480-3d2b-c40f-0901-d5b30b35ea45/pr_source.lsr/100x100bb.jpg",
//      "collectionPrice": 14.99,
//      "trackPrice": 14.99,
//      "trackRentalPrice": 3.99,
//      "collectionHdPrice": 14.99,
//      "trackHdPrice": 14.99,
//      "trackHdRentalPrice": 3.99,
//      "releaseDate": "1984-10-26T07:00:00Z",
//      "collectionExplicitness": "notExplicit",
//      "trackExplicitness": "notExplicit",
//      "trackTimeMillis": 6448697,
//      "country": "USA",
//      "currency": "USD",
//      "primaryGenreName": "Sci-Fi & Fantasy",
//      "contentAdvisoryRating": "R",
//      "longDescription": "A cyborg (part man, part machine) is sent from the 21st century to present-day Los Angeles to assassinate a seemingly innocent women whose child will play an important part in the world from which the killer came.",
//      "hasITunesExtras": true
//    },
//    {
//      "wrapperType": "track",
//      "kind": "feature-movie",
//      "trackId": 1483823959,
//      "artistName": "Tim Miller",
//      "trackName": "Terminator: Dark Fate",
//      "trackCensoredName": "Terminator: Dark Fate",
//      "trackViewUrl": "https://itunes.apple.com/us/movie/terminator-dark-fate/id1483823959?uo=4",
//      "previewUrl": "https://video-ssl.itunes.apple.com/itunes-assets/Video123/v4/c3/31/93/c33193f5-9fe4-1c59-4270-b9906f9ab58a/mzvf_4274757813716744979.640x354.h264lc.U.p.m4v",
//      "artworkUrl30": "https://is5-ssl.mzstatic.com/image/thumb/Video124/v4/2d/ec/8a/2dec8a4e-b4de-c8ab-3769-9151f1b49d00/pr_source.lsr/30x30bb.jpg",
//      "artworkUrl60": "https://is5-ssl.mzstatic.com/image/thumb/Video124/v4/2d/ec/8a/2dec8a4e-b4de-c8ab-3769-9151f1b49d00/pr_source.lsr/60x60bb.jpg",
//      "artworkUrl100": "https://is5-ssl.mzstatic.com/image/thumb/Video124/v4/2d/ec/8a/2dec8a4e-b4de-c8ab-3769-9151f1b49d00/pr_source.lsr/100x100bb.jpg",
//      "collectionPrice": 12.99,
//      "trackPrice": 12.99,
//      "trackRentalPrice": 3.99,
//      "collectionHdPrice": 14.99,
//      "trackHdPrice": 14.99,
//      "trackHdRentalPrice": 3.99,
//      "releaseDate": "2019-11-01T07:00:00Z",
//      "collectionExplicitness": "notExplicit",
//      "trackExplicitness": "notExplicit",
//      "trackTimeMillis": 7724925,
//      "country": "USA",
//      "currency": "USD",
//      "primaryGenreName": "Action & Adventure",
//      "contentAdvisoryRating": "R",
//      "longDescription": "Decades after Sarah Connor (Linda Hamilton) prevented Judgment Day, a lethal new Terminator is sent to eliminate the future leader of the resistance. In a fight to save mankind, battle-hardened Sarah Connor teams up with an unexpected ally (Arnold Schwarzenegger) and an enhanced super soldier to stop the deadliest Terminator yet. Humanity's fate hangs in the balance in this action-packed thrill ride from Tim Miller, the Director of Deadpool, and Producer James Cameron.",
//      "hasITunesExtras": true
//    },
//    {
//      "wrapperType": "track",
//      "kind": "feature-movie",
//      "collectionId": 1499011138,
//      "trackId": 1001326852,
//      "artistName": "Alan Taylor",
//      "collectionName": "Heroínas Poderosas 4 Películas",
//      "trackName": "Terminator Genisys",
//      "collectionCensoredName": "Heroínas Poderosas 4 Películas",
//      "trackCensoredName": "Terminator Genisys",
//      "collectionArtistId": 1008915738,
//      "collectionArtistViewUrl": "https://itunes.apple.com/us/artist/paramount-home-entertainment-inc/1008915738?uo=4",
//      "collectionViewUrl": "https://itunes.apple.com/us/movie/terminator-genisys/id1001326852?uo=4",
//      "trackViewUrl": "https://itunes.apple.com/us/movie/terminator-genisys/id1001326852?uo=4",
//      "previewUrl": "https://video-ssl.itunes.apple.com/itunes-assets/Video122/v4/b3/50/3b/b3503bd3-e21c-ec15-402f-b673415cb85a/mzvf_928488284183513641.640x356.h264lc.U.p.m4v",
//      "artworkUrl30": "https://is4-ssl.mzstatic.com/image/thumb/Video3/v4/e2/dd/81/e2dd81ea-6c2a-1311-c429-efa937678599/pr_source.lsr/30x30bb.jpg",
//      "artworkUrl60": "https://is4-ssl.mzstatic.com/image/thumb/Video3/v4/e2/dd/81/e2dd81ea-6c2a-1311-c429-efa937678599/pr_source.lsr/60x60bb.jpg",
//      "artworkUrl100": "https://is4-ssl.mzstatic.com/image/thumb/Video3/v4/e2/dd/81/e2dd81ea-6c2a-1311-c429-efa937678599/pr_source.lsr/100x100bb.jpg",
//      "collectionPrice": 12.99,
//      "trackPrice": 12.99,
//      "trackRentalPrice": 3.99,
//      "collectionHdPrice": 14.99,
//      "trackHdPrice": 14.99,
//      "trackHdRentalPrice": 3.99,
//      "releaseDate": "2015-07-01T07:00:00Z",
//      "collectionExplicitness": "notExplicit",
//      "trackExplicitness": "notExplicit",
//      "discCount": 1,
//      "discNumber": 1,
//      "trackCount": 4,
//      "trackNumber": 1,
//      "trackTimeMillis": 7566063,
//      "country": "USA",
//      "currency": "USD",
//      "primaryGenreName": "Action & Adventure",
//      "contentAdvisoryRating": "PG-13",
//      "longDescription": "NEW MISSION, NEW THREAT, NEW FATE. \"Arnold is back and better than ever\" (Shawn Edwards, FOX-TV) in this explosive new chapter of the blockbuster Terminator franchise.  In the war of man against machine, Kyle Reese (Jai Courtney, The Divergent Series) is sent back to 1984 by resistance leader John Connor (Jason Clarke, Everest) to protect his young mother, Sarah Connor (Emilia Clarke, Game of Thrones). However, this time unexpected events have altered the past and threaten the future for all mankind. Now Reese must join forces with Sarah and her \"Guardian\" (Arnold Schwarzenegger) to save the world and stop the next evolution of Terminators in \"one of the best action movies of the year.\" (Rick Bentley, The Fresno Bee)",
//      "hasITunesExtras": true
//    },
//    {
//      "wrapperType": "track",
//      "kind": "feature-movie",
//      "collectionId": 343652049,
//      "trackId": 214818692,
//      "artistName": "James Cameron",
//      "collectionName": "Arnold Schwarzenegger Double Feature",
//      "trackName": "Terminator 2: Judgment Day",
//      "collectionCensoredName": "Arnold Schwarzenegger Double Feature",
//      "trackCensoredName": "Terminator 2: Judgment Day",
//      "collectionArtistId": 345356312,
//      "collectionArtistViewUrl": "https://itunes.apple.com/us/artist/lions-gate-films-inc/345356312?uo=4",
//      "collectionViewUrl": "https://itunes.apple.com/us/movie/terminator-2-judgment-day/id214818692?uo=4",
//      "trackViewUrl": "https://itunes.apple.com/us/movie/terminator-2-judgment-day/id214818692?uo=4",
//      "previewUrl": "https://video-ssl.itunes.apple.com/itunes-assets/Video118/v4/74/09/8c/74098c6d-750f-da68-a78e-0a15e82ae667/mzvf_7883043012127296667.640x480.h264lc.U.p.m4v",
//      "artworkUrl30": "https://is1-ssl.mzstatic.com/image/thumb/Video122/v4/01/0b/25/010b25f3-d6bc-63b9-f584-53ddd407638d/pr_source.jpg/30x30bb.jpg",
//      "artworkUrl60": "https://is1-ssl.mzstatic.com/image/thumb/Video122/v4/01/0b/25/010b25f3-d6bc-63b9-f584-53ddd407638d/pr_source.jpg/60x60bb.jpg",
//      "artworkUrl100": "https://is1-ssl.mzstatic.com/image/thumb/Video122/v4/01/0b/25/010b25f3-d6bc-63b9-f584-53ddd407638d/pr_source.jpg/100x100bb.jpg",
//      "collectionPrice": 9.99,
//      "trackPrice": 9.99,
//      "collectionHdPrice": 12.99,
//      "trackHdPrice": 12.99,
//      "releaseDate": "1997-10-22T07:00:00Z",
//      "collectionExplicitness": "notExplicit",
//      "trackExplicitness": "notExplicit",
//      "discCount": 1,
//      "discNumber": 1,
//      "trackCount": 2,
//      "trackNumber": 1,
//      "trackTimeMillis": 8226400,
//      "country": "USA",
//      "currency": "USD",
//      "primaryGenreName": "Action & Adventure",
//      "contentAdvisoryRating": "R",
//      "longDescription": "Arnold Schwarzenegger returns as the Terminator in this explosive action-adventure spectacle. Now he's one of the good guys, sent back in time to protect John Connor, the boy destined to lead the freedom fighters of the future. Linda Hamilton reprises her role as Sarah Connor, John's mother, a quintessential survivor who has been institutionalized for her warning of the nuclear holocaust she knows is inevitable. Together, the threesome must find a way to stop the ultimate enemy-the T-1000, the most lethal Terminator ever created. Co-written, produced and directed by James Cameron (The Terminator, Aliens, Titanic), this visual tour de force is also a touching human story of survival.",
//      "hasITunesExtras": true
//    },
//    {
//      "wrapperType": "track",
//      "kind": "feature-movie",
//      "trackId": 989654025,
//      "artistName": "James Cameron",
//      "trackName": "Terminator 2: Judgment Day (Special Edition)",
//      "trackCensoredName": "Terminator 2: Judgment Day (Special Edition)",
//      "trackViewUrl": "https://itunes.apple.com/us/movie/terminator-2-judgment-day-special-edition/id989654025?uo=4",
//      "previewUrl": "https://video-ssl.itunes.apple.com/itunes-assets/Video111/v4/d0/b1/69/d0b1692a-9907-1b72-8004-50cd7efe0f2c/mzvf_2716900029578081796.640x358.h264lc.U.p.m4v",
//      "artworkUrl30": "https://is5-ssl.mzstatic.com/image/thumb/Video/v4/e9/e0/32/e9e032f9-58cd-6897-8a29-8c49a8faef6e/pr_source.lsr/30x30bb.jpg",
//      "artworkUrl60": "https://is5-ssl.mzstatic.com/image/thumb/Video/v4/e9/e0/32/e9e032f9-58cd-6897-8a29-8c49a8faef6e/pr_source.lsr/60x60bb.jpg",
//      "artworkUrl100": "https://is5-ssl.mzstatic.com/image/thumb/Video/v4/e9/e0/32/e9e032f9-58cd-6897-8a29-8c49a8faef6e/pr_source.lsr/100x100bb.jpg",
//      "collectionPrice": 9.99,
//      "trackPrice": 9.99,
//      "collectionHdPrice": 9.99,
//      "trackHdPrice": 9.99,
//      "releaseDate": "1991-07-03T07:00:00Z",
//      "collectionExplicitness": "notExplicit",
//      "trackExplicitness": "notExplicit",
//      "trackTimeMillis": 9226265,
//      "country": "USA",
//      "currency": "USD",
//      "primaryGenreName": "Sci-Fi & Fantasy",
//      "contentAdvisoryRating": "R",
//      "shortDescription": "Arnold Schwarzenegger reprises his career-changing role as the Terminator in James Cameron's",
//      "longDescription": "Arnold Schwarzenegger reprises his career-changing role as the Terminator in James Cameron's explosive sci-fi hit that was selected as one of AFI's Top Ten Sci-Fi films of all time. In this thrilling sequel, the Terminator is sent back in time to protect John Connor, a boy destined to lead the future freedom fighters. Teaming with Sarah Connor (Linda Hamilton), they must find a way to stop the ultimate enemy.",
//      "hasITunesExtras": true
//    },
//    {
//      "wrapperType": "track",
//      "kind": "feature-movie",
//      "trackId": 338372479,
//      "artistName": "McG",
//      "trackName": "Terminator Salvation (Director's Cut)",
//      "trackCensoredName": "Terminator Salvation (Director's Cut)",
//      "trackViewUrl": "https://itunes.apple.com/us/movie/terminator-salvation-directors-cut/id338372479?uo=4",
//      "previewUrl": "https://video-ssl.itunes.apple.com/itunes-assets/Video128/v4/0c/91/07/0c91078f-f70b-93f8-294f-16fc018cc1c9/mzvf_2986664349710541924.640x354.h264lc.U.p.m4v",
//      "artworkUrl30": "https://is3-ssl.mzstatic.com/image/thumb/Video/5e/ca/f6/mzi.tukmpedg.jpg/30x30bb.jpg",
//      "artworkUrl60": "https://is3-ssl.mzstatic.com/image/thumb/Video/5e/ca/f6/mzi.tukmpedg.jpg/60x60bb.jpg",
//      "artworkUrl100": "https://is3-ssl.mzstatic.com/image/thumb/Video/5e/ca/f6/mzi.tukmpedg.jpg/100x100bb.jpg",
//      "collectionPrice": 9.99,
//      "trackPrice": 9.99,
//      "collectionHdPrice": 9.99,
//      "trackHdPrice": 9.99,
//      "releaseDate": "2009-12-01T08:00:00Z",
//      "collectionExplicitness": "notExplicit",
//      "trackExplicitness": "notExplicit",
//      "trackTimeMillis": 7051583,
//      "country": "USA",
//      "currency": "USD",
//      "primaryGenreName": "Action & Adventure",
//      "contentAdvisoryRating": "R",
//      "longDescription": "Terminator Salvation (Director's Cut) contains explosive additional footage not shown in theaters. The year is 2018. An army of Terminators roams the post-apocalyptic landscape, killing or collecting humans. But small groups of survivors have organized into a Resistance, hiding in underground bunkers and striking when they can. Controlling the Terminators is the artificial intelligence network Skynet, which became self-aware 14 years earlier and turned on its creators, unleashing nuclear annihilation. The world is on the brink of the future that John Connor (Christian Bale) has been warned about all his life. But something totally new has shaken his belief that humanity stands a chance of winning this war: the appearance of Marcus Wright (Sam Worthington), a stranger from the past. As Skynet adapts new strategies to end the Resistance forever, Connor and Marcus must find common ground to take a stand against the onslaught--to infiltrate Skynet and meet the enemy head-on."
//    },
//    {
//      "wrapperType": "track",
//      "kind": "feature-movie",
//      "trackId": 283619485,
//      "artistName": "Jonathan Mostow",
//      "trackName": "Terminator 3: Rise of the Machines",
//      "trackCensoredName": "Terminator 3: Rise of the Machines",
//      "trackViewUrl": "https://itunes.apple.com/us/movie/terminator-3-rise-of-the-machines/id283619485?uo=4",
//      "previewUrl": "https://video-ssl.itunes.apple.com/itunes-assets/Video128/v4/18/6a/e4/186ae424-9d91-f742-ba8a-79a1ae5ac803/mzvf_3187231087805301609.640x480.h264lc.U.p.m4v",
//      "artworkUrl30": "https://is3-ssl.mzstatic.com/image/thumb/Video49/v4/59/67/c4/5967c495-b001-7cd2-4e12-5825ca3da7b1/pr_source.lsr/30x30bb.jpg",
//      "artworkUrl60": "https://is3-ssl.mzstatic.com/image/thumb/Video49/v4/59/67/c4/5967c495-b001-7cd2-4e12-5825ca3da7b1/pr_source.lsr/60x60bb.jpg",
//      "artworkUrl100": "https://is3-ssl.mzstatic.com/image/thumb/Video49/v4/59/67/c4/5967c495-b001-7cd2-4e12-5825ca3da7b1/pr_source.lsr/100x100bb.jpg",
//      "collectionPrice": 12.99,
//      "trackPrice": 12.99,
//      "trackRentalPrice": 3.99,
//      "collectionHdPrice": 12.99,
//      "trackHdPrice": 12.99,
//      "trackHdRentalPrice": 3.99,
//      "releaseDate": "2003-07-02T07:00:00Z",
//      "collectionExplicitness": "notExplicit",
//      "trackExplicitness": "notExplicit",
//      "trackTimeMillis": 6540415,
//      "country": "USA",
//      "currency": "USD",
//      "primaryGenreName": "Action & Adventure",
//      "contentAdvisoryRating": "R",
//      "longDescription": "\"T2\" grossed $204+ million, and now Golden Globe-winner Arnold Schwarzenegger stars in the highly anticipated third chapter in the blockbuster franchise, directed by Jonathon Mostow (\"U571,\" \"From the Earth to the Moon\"). Eight years ago, the machines who rule the future sent an unstoppable Terminator to assassinate the young John Connor. They failed. Now, they're trying again, and Connor must face a female Terminatrix with power over all the machines. But a new T-800 unit Terminator sent back through time will guide him through the coming battle. Golden Globe winner Claire Danes (\"The Hours,\" \"The Mod Squad,\" \"My So-Called Life\") and supermodel Kristanna Loken (\"Panic,\" \"Gangland\") co-star."
//    },
//    {
//      "wrapperType": "track",
//      "kind": "feature-movie",
//      "trackId": 354032593,
//      "artistName": "James Cameron",
//      "trackName": "Terminator 2: Judgement Day",
//      "trackCensoredName": "Terminator 2: Judgement Day",
//      "trackViewUrl": "https://itunes.apple.com/us/movie/terminator-2-judgement-day/id354032593?uo=4",
//      "artworkUrl30": "https://is4-ssl.mzstatic.com/image/thumb/Video/a3/39/d1/mzi.thvxovcw.jpg/30x30bb.jpg",
//      "artworkUrl60": "https://is4-ssl.mzstatic.com/image/thumb/Video/a3/39/d1/mzi.thvxovcw.jpg/60x60bb.jpg",
//      "artworkUrl100": "https://is4-ssl.mzstatic.com/image/thumb/Video/a3/39/d1/mzi.thvxovcw.jpg/100x100bb.jpg",
//      "trackRentalPrice": 3.99,
//      "trackHdRentalPrice": 3.99,
//      "releaseDate": "1991-07-03T07:00:00Z",
//      "collectionExplicitness": "notExplicit",
//      "trackExplicitness": "notExplicit",
//      "country": "USA",
//      "currency": "USD",
//      "primaryGenreName": "Action & Adventure",
//      "contentAdvisoryRating": "R",
//      "longDescription": "Arnold Schwarzenegger is back as the cyborg from the future in one of the most successful sequels of all time. Almost ten years have passed since Sarah Connor's ordeal began, and her son John, the future leader of the resistence, is now a healthy young boy. However, the nightmare begins again when a new, more deadly Terminator is sent back in time, it's orders - to strike at John Conner while he is still a child. Sarah and John, however, don't face this terrifying Terminator alone. The human resistance has sent back another warrior from the future, its orders - to protect John Conner at any cost - the battle for tomorrow has begun..."
//    },
//    {
//      "wrapperType": "track",
//      "kind": "feature-movie",
//      "trackId": 546988566,
//      "artistName": "McG",
//      "trackName": "Terminator Salvation",
//      "trackCensoredName": "Terminator Salvation",
//      "trackViewUrl": "https://itunes.apple.com/us/movie/terminator-salvation/id546988566?uo=4",
//      "previewUrl": "https://video-ssl.itunes.apple.com/itunes-assets/Video127/v4/91/2c/c6/912cc616-4ddd-318c-d2a8-b1e59ce31a02/mzvf_7489840228575507085.640x356.h264lc.U.p.m4v",
//      "artworkUrl30": "https://is4-ssl.mzstatic.com/image/thumb/Video/v4/20/c2/28/20c22867-eeef-3495-b375-0de566f7752b/TerminatorSalvation_1400x2100.jpg/30x30bb.jpg",
//      "artworkUrl60": "https://is4-ssl.mzstatic.com/image/thumb/Video/v4/20/c2/28/20c22867-eeef-3495-b375-0de566f7752b/TerminatorSalvation_1400x2100.jpg/60x60bb.jpg",
//      "artworkUrl100": "https://is4-ssl.mzstatic.com/image/thumb/Video/v4/20/c2/28/20c22867-eeef-3495-b375-0de566f7752b/TerminatorSalvation_1400x2100.jpg/100x100bb.jpg",
//      "collectionPrice": 12.99,
//      "trackPrice": 12.99,
//      "trackRentalPrice": 3.99,
//      "collectionHdPrice": 12.99,
//      "trackHdPrice": 12.99,
//      "trackHdRentalPrice": 3.99,
//      "releaseDate": "2009-05-21T07:00:00Z",
//      "collectionExplicitness": "notExplicit",
//      "trackExplicitness": "notExplicit",
//      "trackTimeMillis": 6877247,
//      "country": "USA",
//      "currency": "USD",
//      "primaryGenreName": "Action & Adventure",
//      "contentAdvisoryRating": "PG-13",
//      "shortDescription": "Judgment Day has come and gone. Modern civilization has been destroyed.An army of Terminators roams",
//      "longDescription": "Judgment Day has come and gone. Modern civilization has been destroyed. An army of Terminators roams the post-apocalyptic landscape, killing orcollecting humans where they hide. But small groups of survivors haveorganized into a Resistance, hiding in underground bunkers and striking when they can against an enemy force that vastly outnumbers them. Onlyone man saw Judgment Day coming, a man whose destiny has always been intertwined with the fate of human existence: John Connor . But something totally new has shaken Connor's belief that humanity has a chance of winning this war: the appearance of Marcus Wright , a stranger from the past whose last memory is of being on death row before awakening in this strange, new world. If humanity is to survive, Connor must decide whether Marcus can be trusted, and the two must find common ground to make a stand against the onslaught and meet the enemy head on."
//    }
//  ]
//}